### ISSUE TITLE
SREF-cnvgrib issue associated with g2

### ISSUE THREAD

**Issue by Hang-Lei-NOAA** [NOAA-EMC/NCEPLIBS-g2#235]
SREF modeling system cannot work with grib_util/v1.2.3. The last version works is grib_util/v1.1.1.
Detailed issue shown is : When use cnvgrib utility to process SREF data, it fails on error message:
 
 pds2pdtens: Couldn:t construct  PDS Template
  Unrecognized Ensemble type =            0           0           0           0

The direct issue associated with this error is: variable kens is not given correct value
kens()     - Ensemble identification for PDS octets 41-45. 
 
Tests with old g2 library (g2/3.0.0; g2/3.1.1) avoid this error.

**Comment by Hang-Lei-NOAA** [comment]
Testing data kept on hcpss:
/NCEPDEV/emc-global/1year/Hang.Lei/testsref
or on hera
/scratch1/NCEPDEV/global/Hang.Lei/testsref
Testing method:
use the cnvgrib utility to do following command:
./cnvgrib -g12 -p40 sref_arw.t09z.pgrb212.ctl.f00  sref_arw.t09z.pgrb212.ctl.f00.grib2

**Comment by kgerheiser** [comment]
How do I access the test data?

**Comment by Hang-Lei-NOAA** [comment]
I add a local access on hera, if this is more convenient.

**Comment by kgerheiser** [comment]
Where at?

Edit: I see it in your edit

**Comment by Hang-Lei-NOAA** [comment]
/scratch1/NCEPDEV/global/Hang.Lei/testsref

**Comment by kgerheiser** [comment]
I am able to reproduce the error on my local machine. Going to dig a little deeper....

**Comment by kgerheiser** [comment]
And I am able to build the develop branch of grib_util with g2 3.1.1 on Hera, and run it without issue. I should now be able to compare where the difference arises.

**Comment by kgerheiser** [comment]
Found something very interesting. This is not actually a g2 issue, at least not directly. The issue is comes from `pdseup`.

When called [here](https://github.com/NOAA-EMC/NCEPLIBS-grib_util/blob/cb892edccc14d2f1ce76f9e5aea03ea57a5544d8/src/cnvgrib/cnv12.F90#L130)

`call pdseup(kens, kprob, xprob, kclust, kmembr, ilast, cgribin(9))`

the output of `kens` when using g2 develop is all zeros. 

See the output of the non-working example, and the working example:

```
kens_pdseup_after = 0 0 0 0 0
kens_pdseup_after = 1 1 2 1 255
```

So, then we look at `pdesup` in W3emc:

https://github.com/NOAA-EMC/NCEPLIBS-w3emc/blob/develop/src/pdseup.f

Not really doing much but calling `gbytec` a bunch of times. Where `gbytec` is declared:

https://github.com/NOAA-EMC/NCEPLIBS-w3emc/blob/develop/src/gbytec.f

So, how would the version of g2 affect `gbytec` if its defined in w3emc? Turns out g2 also has its own version of `gbytec`.

Looking at g2. v3.1.1 it declares `gybtec`:

https://github.com/NOAA-EMC/NCEPLIBS-g2/blob/g2_v3.1.1/src/gbytesc.f

While, the g2 in develop has `g2_gbytec`:

https://github.com/NOAA-EMC/NCEPLIBS-g2/blob/develop/src/g2_gbytesc.F90

Notice the name has been changed to `g2_gbytec`, probably because it doesn't make sense to have the same function defined in different libraries for exactly the reason we encountered here.

With that change in g2 `cnvgrib` is picking up the `gbytec` from w3emc instead. So, there must be something wrong with the function there.

The fix in `cnvgrib` is to either call `g2_gbytec` or fix the function in w3emc. I think the function call in `cnvgrib` should be changed to `g2_gbytec`, and also fix w3emc's `gbytec`.

**Comment by arunchawla-NOAA** [comment]
Nice catch Kyle !

Do we need to have gbytec defined in two places ?

**Comment by kgerheiser** [comment]
A couple of more things to figure out, mainly why the `gbytec` in w3emc does not work. It seems like this behavior was unintentional. With two of the same functions you don't know which one is going to be picked up at link time. It was probably expected that the w3emc version would be used considering it's in the same library.

I don't know if it makes sense to have this function duplicated. It might make sense to move the `gbytes*` functions into bacio (byte IO library). This sure looks like byte io functionality to me. And w3emc and g2 both already link to bacio.

**Comment by Hang-Lei-NOAA** [comment]
We do have a lot of libraries that have overlap. It is not good to move the
gbytes into the bacio. Individually working on G2 needs to use it.

We may first address the cnvgrib issue, then can get a clear map for all.
My previous test by closing w3emc did not help. I was even suspecting that
changes in bacio may result in this, since g2 and w3emc are all built with
bacio and error occurs on get grib index.

**Comment by arunchawla-NOAA** [comment]
what is the rational for the same code being duplicated in different libraries ?

**Comment by Hang-Lei-NOAA** [comment]
They are not exactly duplicates. They are different:
In w3 library:
SUBROUTINE GBYTESC(IN,IOUT,ISKIP,NBYTE,NSKIP,N)

In G2 lib:
subroutine g2_gbytesc(in, iout, iskip, nbyte, nskip, n)     (corrected)

**Comment by kgerheiser** [comment]
You are looking at different functions. `gbytes` with an s is different than `gbytec`.

g2 and w3emc already find/link to bacio, so it wouldn't necessitate any other changes. Not saying do it right at this moment, but I think that's the most logical place to put it so that we only have one copy of this code.

But yes, let's find what's happening here and then we can figure out what to do with gbytec.

**Comment by arunchawla-NOAA** [comment]
ok can you create an issue exploring this ?

**Comment by kgerheiser** [comment]
Narrowed it down a little bit more:

In pdseup, this block is being entered because `ilast` is different.

```
      IF(ILAST.GT.IBYTES) THEN
C    ILAST=IBYTES
      GO TO 333
      ENDIF
```

Old g2:
```
 lgrib =        38891
 ilast_cnvgrib =           45
```

New g2:

```
 lgrib =        38891
 ilast_cnvgrib =       142592
 ilast > ibytes
```

`ilast` is not being filled with the correct value (45) in the new version.

And `ilast` is computed here in a [call to `gbyte` in `cnvgrib12.f`](https://github.com/NOAA-EMC/NCEPLIBS-grib_util/blob/cb892edccc14d2f1ce76f9e5aea03ea57a5544d8/src/cnvgrib/cnv12.F90#L129)

```
call gbyte(cgribin(9), ilast, 0, 24)
```

**Comment by kgerheiser** [comment]
Figured out why the results are different. w3emc `gbyte` expects bytes to be packed into 32-bit integers, while g2_gbyte uses `character(len=1) :: bytes(*)` to store the bytes individually, which is what `cnvgrib` passes to the function.

For example, if I pass the hex value` Z'00002D` (45) to w3emc `gbyte` I can extract the same value as passing `[Z'00', Z'00', Z'2D']` to `g2_gbyte`.

The fix is to update grib_util to call `g2_gbyte`. No other changes are necessary. We can look into extracting these functions into bacio.

**Comment by kgerheiser** [comment]
This is not an error with g2, but with grib_util.

See https://github.com/NOAA-EMC/NCEPLIBS-grib_util/issues/138

**Comment by Hang-Lei-NOAA** [comment]
I test it and confirmed that the change works for SREF.
