### ISSUE TITLE
getting error on build:  "bacio::bacio_4" is imported but not globally visible.

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#240]
```
cmake .. -DCMAKE_PREFIX_PATH="/usr/local/g2c;/usr/local/NCEPLIBS-bacio-2.4.1;/usr/local/jasper-2.0.32"
-- Found bacio: /usr/local/NCEPLIBS-bacio-2.4.1/lib/libbacio_4.a (found version "2.4.1")
CMake Error at CMakeLists.txt:30 (add_library):
  add_library cannot create ALIAS target "bacio::bacio" because target
  "bacio::bacio_4" is imported but not globally visible.


-- Configuring incomplete, errors occurred!
See also "/home/ed/NCEPLIBS-g2/b/CMakeFiles/CMakeOutput.log".
```

@kgerheiser have you seen this before?

**Comment by kgerheiser** [comment]
No, I haven't. It's this line from checking the bacio version: https://github.com/NOAA-EMC/NCEPLIBS-g2/blob/a39d798e84e3ca65d8d128da2dd3c1964a5a9731/CMakeLists.txt#L29-L31

Think we need to tack on a `GLOBAL` at the end there. Or bacio should provide that target for bacio 2.4/2.5 instead of the consumer package.

**Comment by edwardhartnett** [comment]
I'm sorry for my CMake ignorance but I don't understand what you mean by: "Or bacio should provide that target for bacio 2.4/2.5 instead of the consumer package."

Can you elaborate?

Also where would the GLOBAL go and what does it do in this case?

**Comment by kgerheiser** [comment]
I'm actually not sure what's going on here. My comment about `GLOBAL` was incorrect. The error is saying that the target `bacio::bacio_4` which comes from `find_package(bacio)` and the CMake package config it created is not visible globally. You can provide a `GLOBAL` option to `add_library(lib IMPORTED GLOBAL)` so that the target is visble everywhere, else it's just visible in the current directory and subdirectories.

Also, what version of CMake are you using? Aliases to imported targets is a new thing, I think.

**Comment by edwardhartnett** [comment]
```
cmake --version
cmake version 3.16.3

```

**Comment by kgerheiser** [comment]
Ah, that's it. CMake 3.16 does not support this feature.

https://cmake.org/cmake/help/latest/command/add_library.html#id6


> New in version 3.18: An ALIAS can target a non-GLOBAL Imported Target. Such alias is scoped to the directory in which it is created and below. The [ALIAS_GLOBAL](https://cmake.org/cmake/help/latest/prop_tgt/ALIAS_GLOBAL.html#prop_tgt:ALIAS_GLOBAL) target property can be used to check if the alias is global or not.

**Comment by edwardhartnett** [comment]
OK, so I need to update the minimum required CMake in the CMakeLists.txt file at the top level, which currently has:

`cmake_minimum_required(VERSION 3.15)
`

**Comment by kgerheiser** [comment]
Yes, and I think we put this check in a couple of projects.

**Comment by edwardhartnett** [comment]
Well I tried to upgrade cmake by upgrading my version of Ubuntu and broke my internet. Sigh...

**Comment by kgerheiser** [comment]
I would build a new version of CMake or download a binary from https://cmake.org/download/
