### ISSUE TITLE
need to require a specific minimum jasper version in cmake (and it's version 2.0.25)

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#45]
We need to require a specific jasper version.

**Comment by kgerheiser** [comment]
Do it need to require a specific version or can it be a range? I looked at the history and the bug appears in Jasper 1.900.19 (2016), and was fixed in 2.0.25, and it only happens with the Intel compiler. 

Should it be a more customized check like if Jasper is a broken version and if using Intel?

In addition, there should be a test in g2 that fails when using a broken version of Jasper.

**Comment by edwardhartnett** [comment]
We can supply a range, a specific version, or a minimum version. I think we want to supply a minimum version usually.

Yes we can also add specific checks for known problem combinations.

As for the test, that would normally be true, but since we have no tests I think it's expecting too much. However, if you have an easy test, we can use some for this repo.

**Comment by edwardhartnett** [comment]
In this case, let's require jasper 2.0.25. Would that work? That's what we install with hpc-stack right now.

@kgerheiser any thoughts?
